### ISSUE TITLE
Type of universityRankingRange is incorrect in usage of UserPreferences in ServerProfileDataAccessObject

### ISSUE THREAD

**Issue by kanishsharma** [LatinScribe/CSC207-Project#120]
In the try body of the getProfile() function in ServerProfileDataAccessObject, the typing and functions used are on an ArrayList object instead of a finite list of integers Integers[]. There's going to be some typing errors when I try to use that function to return profiles, so the functions used to format the input from the responseBody are going to have to be manipulated somewhat

**Comment by LatinScribe** [comment]
Should be fixed, see #129
