### ISSUE TITLE
ProfileDataAccessInterface returns UserPreferences instead of UserProfileOutputData

### ISSUE THREAD

**Issue by kanishsharma** [LatinScribe/CSC207-Project#121]
Small change here, since both seem to be formatted about the same, but UserProfileOutputData should be the main output for getProfile() instead of UserPreferences - the latter isn't used that much and will likely be removed, since I've been using UserProfileOutputData instead of UserPreferences.

**Comment by LatinScribe** [comment]
Fixed I think? By CA, I think it should just return the userPreferences, and the interactor returns the user profile output data, maybe i'm wrong though, need to double check CA

**Comment by LatinScribe** [comment]
See #129
