### ISSUE TITLE
Minor issue with typing: Should be Integer[] instead of Int

### ISSUE THREAD

**Issue by kanishsharma** [LatinScribe/CSC207-Project#131]
Small issue on your branch changes that I didn't immediately notice - the typing for universityRankingRange should be Integer[] not int[]. If you could make that small change, everything should be working fine

**Comment by LatinScribe** [comment]
Why not use int[]? It's more efficient, I made the swap from integer[] to int[] intentionally. If you don't specifically need it as an object, then we can just use int[], it's easier

**Comment by kanishsharma** [comment]
Got it, will change that implementation on my end

**Comment by kanishsharma** [comment]
Minor issue I noticed while changing the typing - saveProfile still uses Integer[], meaning that the ServerProfileDAO and the ProfileDataAccessInterface are both using Integer[] for the universityRankingRange - changed that in my commits but just wanted to let you know if there's anything else that relies on those functions that might be affected
