### ISSUE TITLE
BasicQuery only returns the first 20 search results if more than 20 results exist

### ISSUE THREAD

**Issue by aclin05** [LatinScribe/CSC207-Project#141]
Example: Put "New York" into the search box and only the first 20 schools will be returned

**Comment by LatinScribe** [comment]
Right, I remember this being an issue, forgot to fix! I'll work on modifying it to pull more pages

**Comment by LatinScribe** [comment]
Fixed, simply pass in either "&page=pgnum" or "&per_page=100" for more results
